from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_pdf(data, ai_response, score_data):
    # Create filename with date and time
    filename = f"medicheck_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    story = []
    
    # Title style
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#2C3E50"),
        spaceAfter=10,
        alignment=1  # center
    )
    
    # Subtitle style
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#7F8C8D"),
        spaceAfter=20,
        alignment=1
    )
    
    # Section header style
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#2980B9"),
        spaceBefore=15,
        spaceAfter=8
    )
    
    # Body style
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#2C3E50"),
        spaceAfter=6,
        leading=16
    )

    # ── HEADER ──
    story.append(Paragraph("🏥 MediCheck Report", title_style))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        subtitle_style
    ))
    story.append(Spacer(1, 0.2 * inch))

    # ── PATIENT INFO TABLE ──
    story.append(Paragraph("Patient Information", section_style))
    
    patient_data = [
        ["Symptoms", data["symptoms"]],
        ["Duration", data["duration"]],
        ["Discomfort Level", data["severity"].capitalize()],
    ]
    
    patient_table = Table(patient_data, colWidths=[2*inch, 4.5*inch])
    patient_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#2980B9")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("BACKGROUND", (1, 0), (1, -1), colors.HexColor("#EBF5FB")),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("PADDING", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (1, 0), (1, -1), [colors.HexColor("#EBF5FB"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#AED6F1")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    
    story.append(patient_table)
    story.append(Spacer(1, 0.2 * inch))

    # ── SEVERITY SCORE ──
    story.append(Paragraph("Severity Assessment", section_style))
    
    # Pick color based on score
    if score_data["score"] >= 70:
        score_color = "#E74C3C"  # red
    elif score_data["score"] >= 40:
        score_color = "#F39C12"  # orange
    else:
        score_color = "#27AE60"  # green
    
    score_style = ParagraphStyle(
        "Score",
        parent=styles["Normal"],
        fontSize=13,
        textColor=colors.HexColor(score_color),
        spaceAfter=6,
        fontName="Helvetica-Bold"
    )
    
    story.append(Paragraph(f"Score: {score_data['score']}/100", score_style))
    story.append(Paragraph(f"Assessment: {score_data['severity_level']}", body_style))
    
    # Flags
    if score_data["flags"]:
        story.append(Spacer(1, 0.1 * inch))
        for flag in score_data["flags"]:
            flag_style = ParagraphStyle(
                "Flag",
                parent=styles["Normal"],
                fontSize=11,
                textColor=colors.HexColor("#E74C3C"),
                spaceAfter=4
            )
            story.append(Paragraph(flag, flag_style))
    
    story.append(Spacer(1, 0.2 * inch))

    # ── AI ANALYSIS ──
    story.append(Paragraph("AI Analysis", section_style))
    
    # Clean up AI response and add line by line
    for line in ai_response.split("\n"):
        if line.strip():
            story.append(Paragraph(line.strip(), body_style))
    
    story.append(Spacer(1, 0.3 * inch))

    # ── DISCLAIMER ──
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#95A5A6"),
        spaceAfter=6,
        alignment=1
    )
    story.append(Paragraph(
        "⚠️ This report is generated by AI and is not a substitute for professional medical advice. "
        "Always consult a qualified doctor for proper diagnosis and treatment.",
        disclaimer_style
    ))

    # Build PDF
    doc.build(story)
    print(f"✅ PDF report saved as: {filename}")
    return filename